---
- name: Upgrade apt packages
  apt: upgrade=dist
       update_cache=yes

- name: Install NTP
  apt: pkg=ntp

- name: Install prerequisite packages
  apt: pkg={{ item }}
  with_items:
    - autoconf
    - build-essential
    - python-setuptools
    - python-software-properties
    - python-dev
    - python-pip
    - libncurses-dev

# CIS CAT secuirty configurations

- name: crontab owner and group
  shell: "chown root:root /etc/cron* && sudo chmod og-rwx /etc/cron*"
  become: true
  tags:
    - cis_cat_security
    - crontab

- name: Check that the at.allow exists
  stat: path=/etc/at.allow
  register: at_allow
  tags:
    - cis_cat_security
    - cron

- name: restrict cron to users
  shell: "rm /etc/*.deny && touch /etc/cron.allow && touch /etc/at.allow && chmod og-rwx /etc/cron.allow && chmod og-rwx /etc/cron.allow && chmod og-rwx /etc/at.allow && sudo chown root:root /etc/cron.allow && sudo chown root:root /etc/at.allow"
  become: true
  when: at_allow.stat.exists == False
  tags:
    - cis_cat_security
    - cron

- name: ssh config permissisons
  shell: "chown root:root /etc/ssh/sshd_config && sudo chmod 600 /etc/ssh/sshd_config"
  become: true
  tags:
    - cis_cat_security
    - ssh

- name: ssh x11 forwarding
  lineinfile: dest=/etc/ssh/sshd_config regexp=^X11Forwarding line="X11Forwarding no"
  become: true
  tags:
    - cis_cat_security
    - ssh

- name: ssh max auth tries
  lineinfile: dest=/etc/ssh/sshd_config regexp=^MaxAuthTries line="MaxAuthTries 4"
  become: true
  tags:
    - cis_cat_security
    - ssh

- name: diable root login
  lineinfile: dest=/etc/ssh/sshd_config regexp=^PermitRootLogin line="PermitRootLogin no"
  become: true
  tags:
    - cis_cat_security
    - ssh

- name: diable user environments
  lineinfile: dest=/etc/ssh/sshd_config regexp=^PermitUserEnvironment line="PermitUserEnvironment no"
  become: true
  tags:
    - cis_cat_security
    - ssh

- name: limit ssh ciphers
  lineinfile: dest=/etc/ssh/sshd_config regexp=^Ciphers line="Ciphers aes128-ctr,aes192-ctr,aes256-ctr"
  become: true
  tags:
    - cis_cat_security
    - ssh

- name: ssh ClientAliveCountMax times
  lineinfile: dest=/etc/ssh/sshd_config regexp=^ClientAliveCountMax line="ClientAliveCountMax 0" state=present
  become: true
  tags:
    - cis_cat_security
    - ssh

- name: ssh ClientAliveInterval times
  lineinfile: dest=/etc/ssh/sshd_config regexp=^ClientAliveInterval line="ClientAliveInterval 300" state=present
  become: true
  tags:
    - cis_cat_security
    - ssh

- name: update host names
  lineinfile: dest=/etc/ssh/sshd_config regexp=^AllowUsers line="AllowUsers {{user}}" state=present
  become: true
  tags:
    - cis_cat_security
    - ssh

- name: IPV6 router ads all
  lineinfile: dest=/etc/sysctl.conf regexp=^net.ipv6.conf.all.accept_ra line="net.ipv6.conf.all.accept_ra=0" state=present
  become: true
  tags:
    - cis_cat_security
    - sysctl

- name: IPV6 router ads default
  lineinfile: dest=/etc/sysctl.conf regexp=^net.ipv6.conf.default.accept_ra line="net.ipv6.conf.default.accept_ra = 0" state=present
  become: true
  tags:
    - cis_cat_security
    - sysctl

- name: IPV6 router ads kernal
  shell: "sysctl -w net.ipv6.conf.all.accept_ra=0 && sysctl -w net.ipv6.conf.default.accept_ra=0 && sysctl -w net.ipv6.route.flush=1"
  become: true
  tags:
    - cis_cat_security
    - sysctl

- name: IPV6 redirect acceptance
  lineinfile: dest=/etc/sysctl.conf regexp=^net.ipv6.conf.default.accept_redirects line="net.ipv6.conf.default.accept_redirects = 0"
  become: true
  tags:
    - cis_cat_security
    - sysctl

- name: IPV6 redirect acceptance kernal
  shell: "sysctl -w net.ipv6.conf.all.accept_redirects=0 && sysctl -w net.ipv6.conf.default.accept_redirects=0 && sysctl -w net.ipv6.route.flush=1"
  become: true
  tags:
    - cis_cat_security
    - sysctl

- name: IPV6 disable
  lineinfile: dest=/etc/sysctl.conf regexp=^net.ipv6.conf.lo.disable_ipv6 line="net.ipv6.conf.lo.disable_ipv6 = 1"
  become: true
  notify: Restart Sysctl
  tags:
    - cis_cat_security
    - sysctl

- name: ICMP redirect acceptance all
  lineinfile: dest=/etc/sysctl.conf regexp=^net.ipv4.conf.all.secure_redirects line="net.ipv4.conf.all.secure_redirects = 0"
  become: true
  tags:
    - cis_cat_security
    - sysctl

- name: ICMP redirect acceptance defaults
  lineinfile: dest=/etc/sysctl.conf regexp=^net.ipv4.conf.default.secure_redirects line="net.ipv4.conf.default.secure_redirects = 0"
  become: true
  tags:
    - cis_cat_security
    - sysctl

- name: ICMP redirect acceptance kernal
  shell: "sysctl -w net.ipv4.conf.all.secure_redirects=0 && sysctl -w net.ipv4.conf.default.secure_redirects=0 && sysctl -w net.ipv4.route.flush=1"
  become: true
  tags:
    - cis_cat_security
    - sysctl

- name: Log suspicious packets defaults
  lineinfile: dest=/etc/sysctl.conf regexp=^net.ipv4.conf.default.log_martians line="net.ipv4.conf.default.log_martians = 1" state=present
  become: true
  tags:
    - cis_cat_security
    - sysctl

- name: Log suspicious packets all
  lineinfile: dest=/etc/sysctl.conf regexp=^net.ipv4.conf.all.log_martians line="net.ipv4.conf.all.log_martians = 1" state=present
  become: true
  tags:
    - cis_cat_security
    - sysctl

- name: Log suspicious packets kernal
  shell: "sysctl -w net.ipv4.conf.all.log_martians=1 && sysctl -w net.ipv4.conf.default.log_martians=1 && sysctl -w net.ipv4.route.flush=1"
  become: true
  tags:
    - cis_cat_security
    - sysctl

- name: Enable SYN cookies
  lineinfile: dest=/etc/sysctl.conf regexp=^net.ipv4.tcp_syncookies line="net.ipv4.tcp_syncookies = 1" state=present
  become: true
  tags:
    - cis_cat_security
    - sysctl

- name: Enable SYN cookies kernal
  shell: "sysctl -w net.ipv4.tcp_syncookies=1 && sysctl -w net.ipv4.route.flush=1"
  become: true
  tags:
    - cis_cat_security
    - sysctl

- name: Disable packets redirects defaults
  lineinfile: dest=/etc/sysctl.conf regexp=^net.ipv4.conf.default.send_redirects line="net.ipv4.conf.default.send_redirects = 0" state=present
  become: true
  tags:
    - cis_cat_security
    - sysctl

- name: Disable packets redirects all
  lineinfile: dest=/etc/sysctl.conf regexp=^net.ipv4.conf.all.send_redirects line="net.ipv4.conf.all.send_redirects = 0" state=present
  become: true
  tags:
    - cis_cat_security
    - sysctl

- name: Disable packets redirects kernal
  shell: "sysctl -w net.ipv4.conf.all.send_redirects=0 && sysctl -w net.ipv4.conf.default.send_redirects=0 && sysctl -w net.ipv4.route.flush=1"
  become: true
  tags:
    - cis_cat_security
    - sysctl


- name: core dumps sysctl
  lineinfile: dest=/etc/sysctl.conf line="fs.suid_dumpable = 0" state=present
  tags:
    - cis_cat_security
    - sysctl

- name: create hosts deny file
  file: path=/etc/hosts.deny state=touch owner=root group=root mode=644
  tags:
    - cis_cat_security
    - hosts

- name: Create CIS conf file
  template: src=cis_conf.j2 dest=/etc/modprobe.d/CIS.conf
  become: true
  tags:
    - cis_cat_security
    - cis_conf

- name: bootloader config permissisons
  shell: chmod og-rwx /boot/grub/grub.cfg
  become: true
  tags:
    - cis_cat_security
    - bootloader

- name: install ubuntu Firewall
  apt: name=ufw state=present update_cache=yes
  tags:
    - cis_cat_security
    - ufw

- name: enable ufw
  shell: yes | ufw enable
  tags:
    - cis_cat_security
    - ufw

- name: enable ufw ports
  shell: "sudo ufw allow 22/tcp && sudo ufw allow 8080/tcp && sudo ufw allow 443/tcp"
  tags:
    - cis_cat_security
    - ufw

- name: Ensure MOTD does not allow group write access
  file: path=/etc/motd state=touch owner=root group=root mode=644
  become: true
  tags:
    - cis_cat_security
    - motd

- name: Create MOTD on issue.net
  template: src=motd_banner.j2 dest=/etc/issue.net owner=root group=root mode=644
  become: true
  tags:
    - cis_cat_security
    - motd

- name: set ssh banner
  shell: "sed -i '/^#Banner /s/^#//' /etc/ssh/sshd_config"
  become: true
  tags:
    - cis_cat_security
    - motd

- name: disable x window
  apt:
    name: xserver-xorg-core*
    state: absent
  tags:
    - cis_cat_security
    - x_window

- name: disable apport
  lineinfile: dest=/etc/init/apport.conf regexp="^env enabled" line="env enabled=0"
  become: true
  tags:
    - cis_cat_security
    - apport

- name: disable apport service
  service: name=apport enabled=no state=stopped
  become: true
  tags:
    - cis_cat_security
    - apport


- name: disable rpc bind
  lineinfile: dest=/etc/init/rpcbind-boot.conf line="start on virtual-filesystems and net-device-up IFACE=lo" state=absent
  tags:
    - cis_cat_security
    - rpcbind-boot


- name: restrict core dumps
  lineinfile: dest=/etc/security/limits.conf line="* hard core 0" state=present
  tags:
    - cis_cat_security
    - core_dumps


- name: limit password reuse
  lineinfile: dest=/etc/pam.d/common-password line="password sufficient pam_unix.so remember=5" state=present
  tags:
    - cis_cat_security
    - password_limits

- name: password complexity
  lineinfile: dest=/etc/pam.d/common-password line="password required pam_cracklib.so retry=3 minlen=14 dcredit=-1 ucredit=-1 ocredit=-1 lcredit=-1" state=present
  tags:
    - cis_cat_security
    - password_limits

- name: password failed lockout
  lineinfile: dest=/etc/pam.d/login line="auth required pam_tally2.so onerr=fail audit silent deny=5 unlock_time=900" state=present
  tags:
    - cis_cat_security
    - password_limits

- name: disable cramfs
  lineinfile: dest=/etc/modprobe.d/CIS.conf line="install cramfs /bin/true" state=present
  tags:
    - cis_cat_security
    - disable_file_systems

- name: disable freevxfs
  lineinfile: dest=/etc/modprobe.d/CIS.conf line="install freevxfs /bin/true" state=present
  tags:
    - cis_cat_security
    - disable_file_systems

- name: disable jffs2
  lineinfile: dest=/etc/modprobe.d/CIS.conf line="install jffs2 /bin/true" state=present
  tags:
    - cis_cat_security
    - disable_file_systems

- name: disable hfs
  lineinfile: dest=/etc/modprobe.d/CIS.conf line="install hfs /bin/true" state=present
  tags:
    - cis_cat_security
    - disable_file_systems

- name: disable hfsplus
  lineinfile: dest=/etc/modprobe.d/CIS.conf line="install hfsplus /bin/true" state=present
  tags:
    - cis_cat_security
    - disable_file_systems

- name: disable squashfs
  lineinfile: dest=/etc/modprobe.d/CIS.conf line="install squashfs /bin/true" state=present
  tags:
    - cis_cat_security
    - disable_file_systems

- name: disable udf
  lineinfile: dest=/etc/modprobe.d/CIS.conf line="install udf /bin/true" state=present
  tags:
    - cis_cat_security
    - disable_file_systems

- name: disable FAT
  lineinfile: dest=/etc/modprobe.d/CIS.conf line="install vfat /bin/true" state=present
  tags:
    - cis_cat_security
    - disable_file_systems

- name: uninstall telnet
  apt: name=telnet state=absent update_cache=yes
  tags:
    - cis_cat_security
    - disable_telnet